version: "3.9"
services:
  db:
    image: postgres:16
    container_name: go_backend_db
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_pass
      POSTGRES_DB: go_backend
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_backend_app
    environment:
      DB_HOST: db
      DB_USER: go_user
      DB_PASSWORD: go_pass
      DB_NAME: go_backend
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  db_data:
